# Generated by Django 2.2 on 2020-07-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200719_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.FileField(blank=True, default='/static/img/indir.jpg', null=True, upload_to='images/', verbose_name='Profil İmage'),
        ),
    ]
