# Generated by Django 2.2 on 2020-08-03 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[(0, 'Python'), (1, 'Java'), (2, 'Javascript'), (3, 'Linux'), (4, 'Css'), (5, 'Html'), (6, 'React'), (7, 'Devops')], max_length=100, null=True),
        ),
    ]
