# Generated by Django 2.2 on 2020-07-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default='/static/img/post-sample-image.jpg', null=True, upload_to='images/', verbose_name='İmage'),
        ),
    ]
