# Generated by Django 2.2 on 2020-07-20 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200720_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, default='/images/post-sample-image.jpg', null=True, upload_to='images/', verbose_name='Post İmage'),
        ),
    ]
