# Generated by Django 2.2 on 2020-07-22 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('blog', '0007_auto_20200721_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_parent', models.BooleanField(default=False)),
                ('object_id', models.PositiveIntegerField()),
                ('comment_content', models.TextField(max_length=1000, null=True, verbose_name='Yorum')),
                ('comment_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('comment_author', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name_plural': 'İç içe yorum sistemi',
            },
        ),
    ]
