# Generated by Django 2.2 on 2020-07-22 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_newcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newcomment',
            options={'verbose_name_plural': 'iç içe yorum'},
        ),
    ]
