# Generated by Django 2.2 on 2020-07-23 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_favoriteblog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoriteblog',
            old_name='blog',
            new_name='post',
        ),
    ]
