# Generated by Django 2.2 on 2020-07-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200728_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.PositiveIntegerField(choices=[(0, 'Python'), (1, 'Java'), (2, 'Javascript'), (3, 'Linux'), (4, 'Css'), (5, 'Html'), (6, 'React'), (7, 'Devops')], null=True),
        ),
    ]
