# Generated by Django 2.2 on 2020-07-28 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200728_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='blog.Post'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.PositiveIntegerField(choices=[(0, 'Python'), (1, 'Java'), (2, 'Javascript'), (3, 'Linux'), (4, 'Css'), (5, 'Html'), (6, 'React'), (7, 'Devops')], null=True),
        ),
    ]
